In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
results_df = pd.read_csv("football_results/results.csv",encoding="utf-8")
goal_scorers_df = pd.read_csv("football_results/goalscorers.csv",encoding="utf-8")
shotout_df = pd.read_csv("football_results/shootouts.csv",encoding="utf-8")

In [3]:
results_df.head(5)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [4]:
results_df.shape

(49477, 9)

In [5]:
results_df["tournament"].value_counts()

tournament
Friendly                                18388
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1036
                                        ...
Copa Confraternidad                         1
Benedikt Fontana Cup                        1
ConIFA Challenger Cup                       1
CONIFA World Cup qualification              1
South Asian Super Cup                       1
Name: count, Length: 200, dtype: int64

In [6]:
goal_scorers_df.head(5)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False

In [7]:
merged_df = pd.merge(right=results_df,left=goal_scorers_df,on=["date","home_team","away_team"],how="left")

In [8]:
merged_df.head(5)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty,home_score,away_score,tournament,city,country,neutral
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False,0.0,4.0,Copa América,Buenos Aires,Argentina,True
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False,0.0,4.0,Copa América,Buenos Aires,Argentina,True
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False,0.0,4.0,Copa América,Buenos Aires,Argentina,True
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False,0.0,4.0,Copa América,Buenos Aires,Argentina,True
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False,6.0,1.0,Copa América,Buenos Aires,Argentina,False

In [9]:
merged_df.shape

(47620, 14)

In [10]:
merged_df.isna().sum()

date            0
home_team       0
away_team       0
team            0
scorer         48
minute        256
own_goal        0
penalty         0
home_score      0
away_score      0
tournament      0
city            0
country         0
neutral         0
dtype: int64

In [11]:
na_df = merged_df["date"].isna()

0        False
1        False
2        False
3        False
4        False
         ...
47615    False
47616    False
47617    False
47618    False
47619    False
Name: date, Length: 47620, dtype: bool