In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
results_df = pd.read_csv("football_results/results.csv",encoding="utf-8")
goal_scorers_df = pd.read_csv("football_results/goalscorers.csv",encoding="utf-8")
shotout_df = pd.read_csv("football_results/shootouts.csv",encoding="utf-8")

In [14]:
results_df.shape

(49477, 9)

In [3]:
results_df.head(5)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [15]:
results_df.isna().sum()

date           0
home_team      0
away_team      0
home_score    64
away_score    64
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [4]:
results_df.shape

(49477, 9)

In [5]:
results_df["tournament"].value_counts()

tournament
Friendly                                18388
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1036
                                        ...
Copa Confraternidad                         1
Benedikt Fontana Cup                        1
ConIFA Challenger Cup                       1
CONIFA World Cup qualification              1
South Asian Super Cup                       1
Name: count, Length: 200, dtype: int64

In [25]:
results_df["neutral"].value_counts()

neutral
False    36356
True     13121
Name: count, dtype: int64

In [16]:
results_df.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [22]:
results_df = results_df.sort_values("date",ascending=True)
test_df = results_df.head(20)

In [23]:
test_df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
5,1876-03-25,Scotland,Wales,4.0,0.0,Friendly,Glasgow,Scotland,False
6,1877-03-03,England,Scotland,1.0,3.0,Friendly,London,England,False
7,1877-03-05,Wales,Scotland,0.0,2.0,Friendly,Wrexham,Wales,False
8,1878-03-02,Scotland,England,7.0,2.0,Friendly,Glasgow,Scotland,False
9,1878-03-23,Scotland,Wales,9.0,0.0,Friendly,Glasgow,Scotland,False
10,1879-01-18,England,Wales,2.0,1.0,Friendly,London,England,False
11,1879-04-05,England,Scotland,5.0,4.0,Friendly,London,England,False
12,1879-04-07,Wales,Scotland,0.0,3.0,Friendly,Wrexham,Wales,False
13,1880-03-13,Scotland,England,5.0,4.0,Friendly,Glasgow,Scotland,False
14,1880-03-15,Wales,England,2.0,3.0,Friendly,Wrexham,Wales,False
15,1880-03-27,Scotland,Wales,5.0,1.0,Friendly,Glasgow,Scotland,False
16,1881-02-26,England,Wales,0.0,1.0,Friendly,Blackburn,England,False
17,1881-03-12,England,Scotland,1.0,6.0,Friendly,London,England,False
18,1881-03-14,Wales,Scotland,1.0,5.0,Friendly,Wrexham,Wales,False
19,1882-02-18,Northern Ireland,England,0.0,13.0,Friendly,Belfast,Ireland,False

In [36]:
starting_elo = 1500
unique_home_t = list(test_df["home_team"].unique())
unique_away_t = list(test_df["away_team"].unique())
all_t = unique_home_t + unique_away_t
all_t = np.array(all_t)
all_t = np.unique(all_t)

In [37]:
all_t

array(['England', 'Northern Ireland', 'Scotland', 'Wales'], dtype='<U16')

In [40]:
elos = {}
for t in all_t:
    elos[str(t)] = starting_elo
elos

{'England': 1500, 'Northern Ireland': 1500, 'Scotland': 1500, 'Wales': 1500}

In [41]:
test_df.shape

(20, 9)

In [50]:
for i in range(test_df.shape[0]):
    row = test_df.loc[i,:]
    home_t = row["home_team"]
    home_score = row["home_score"]
    away_t = row["away_team"]
    away_score = row["away_score"]
    if home_score > away_score:
        winner = "home"
    elif home_score == away_score:
        winner = "draw"
    else:
        winner = "away"
    print(winner)

draw
home
home
draw
home
home
away
away
home
home
home
home
away
home
away
home
away
away
away
away